### ISSUE TITLE
problem with setHTML and getHTML

### ISSUE THREAD

**Issue by shawnarvin** [ether/ep_font_size#11]
We use an external data source for our documents and use etherpad for collaborative editing. In order to integrate etherpad into our system we are planning to use the etherpad apis to create a pad and set the content using the setHTML api and once done use the getHTML to capture the content and save it back to our system. The problem we are running into the styles are not honored on the setHTML. On the other side the getHTML does not return the styles and therefore making the result HTML useless for use in other HTML based clients. I noticed that doing a HTML export from the etherpad client returns the styles which is not the case for the getHTML. I am using the font size as an example but there are other formatting and styling requirements that we must maintain as we bring in/out documents to and from etherpad. What are we missing or doing wrong to avoid these issues?

Thank you
Shawn

**Comment by JohnMcLear** [comment]
I can only really look at the font size stuff within this scope, I'm available as a gun for hire if you need direct support and that's pretty much the best way to get me onto projects.  Apologies if this is less helpful than you were hoping for! :)

**Comment by JohnMcLear** [comment]
Should be fixed now, give me a shout if not.
