### ISSUE TITLE
Once set, Font Size gets forgotten

### ISSUE THREAD

**Issue by Samurai88** [ether/ep_font_size#15]
1. When setting a font size manually to say 18, then any new text that is written/added in the middle or at the end of the document gets the default (smaller) font size.

2. When copying a portion of the text (which has font size 18) and pasting it elsewhere in the same page, resets the fontsize back to the default (smaller) font size.

This happens all the time and is a consistent bug. Apart from this little annoyance its a very very nice opensource realtime texteditor! Tested in FireFox 50 on a Windows 10 64 bit machine.

----

(im forwarding this from here where I originally opened the topic, where lpagliari suggested me to post it here instead so....  https://github.com/ether/etherpad-lite/issues/3200

**Comment by JohnMcLear** [comment]
@Samurai88 can you replicate now?  We changed how we handle this.  We don't support setting an attribute IE size then typing but if you type and keep typing with some size X font it should continue keeping that font.
