### ISSUE TITLE
Size 9 and 10 are not working

### ISSUE THREAD

**Issue by poafernandes** [ether/ep_font_size#16]
I was testing the font size and I saw that size 9 and 10 were not working properly on my instance of etherpad.

Then I went to test on Etherpad's sandstorm demo and was not working there either.
Both 9 and 10 have the same size as 15

![image](https://user-images.githubusercontent.com/30806203/44594797-894c8e80-a79d-11e8-8f28-a9dae297c001.png)

**Comment by felipesvianna** [comment]
You need to change the first two lines in iframe.css file like this:
```
fs8{font-size:8px;}
fs9{font-size:9px;}
```
The the semicolons were wrongly placed.

**Comment by JohnMcLear** [comment]
Pull request welcome!
