### ISSUE TITLE
Button Icon is missing

### ISSUE THREAD

**Issue by lisandi** [ether/ep_font_size#41]
It would be great and more useful to display a Button Icon in the Button bar instead of the Text which clutters the "Button" Bar. A click on the Button could open up the Menu so people can choose from it. The chosen format could get highlighted as replacing it with a long text would crash the Button bar completely.

By Hover or longer Tapping with the finger (on tablet/phone), the actual chosen value could be shown in the title tag.
![Screen Shot 2021-10-01 at 19 37 27](https://user-images.githubusercontent.com/1982011/135620902-c1b6ac1f-fccb-4e5a-934c-fac3352f0b73.png)

**Comment by JohnMcLear** [comment]
This was the initial design and it was found to be lacking for accessibility so we changed to this select.

**Comment by lisandi** [comment]
Accessibility can be achieved with the aria label like it is done by the developer of i.e. image_upload

<li class="separator acl-write"></li>

<li data-type="button" data-key="imageUpload" data-l10n-id="ep_image_upload.toolbar.image_upload.title">
  <a class="grouped-left ep_image_upload" data-align="0" data-l10n-id="ep_image_upload.toolbar.image_upload.title" title="Upload Image" aria-label="Upload Image">
    <button class="buttonicon ep_image_upload image_upload buttonicon-picture" data-align="0" aria-label="Upload Image"></button>
  </a>
</li>

Here you also don't write "Image Upload" so if that would be an argument that Image Upload would definitely need to be called "ImageUpload" instead. Now imagine how cluttered the Button Bar would become when it would be suddenly a "TextBar" instead.

In the same way, an ICON could be added to any Select Dropdown. 
Replace additionally that "Try Me! in the example with an image and you have an accessible Icon dropdown Menu.
https://sparksuite.github.io/react-accessible-dropdown-menu-hook/demo/
Delete the Try Me and the Downward arrow stays - and could be also an icon for any of those dropdown option box headers

or in Vue
https://vue-select.org/
