### ISSUE TITLE
Export will cause abiword to crash

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_font_size#8]
I had a temp fix in place but it wasn't async, see https://github.com/ether/etherpad-lite/pull/2494

**Comment by JohnMcLear** [comment]
I bumped Egil about this, imho we need an aCallAllSeries hook method..  The problem (if you want to call it that) is that aCallAll processes in parallel..  So if you have this string..

``foo`` and you want to edit it in 2 plugins..  

Let's say plugin 1 wants to ``/s/foo/boo`` 

Let's say plugin 2 wants to ``/s/boo/moo``

The aCallAll will return ``boo`` for plugin one and `foo` for plugin two.

**Comment by JohnMcLear** [comment]
I attempted to create an ``aCallSeries`` method in ``hooks.js`` switching out the map for mapSeries but I seem to get similar output..

**Comment by afamiglietti** [comment]
I notice the async code to reformat the html output doesn't seem to be working. I uncommented the get LineHTMLForOutput hook and that works, but of course if you have two plugins using the hook you get duplicate output lines using this technique. 

I'd like to try to sort this out, any advice for moving forward?

**Comment by JohnMcLear** [comment]
@afamiglietti we need to add a aCallSeries method but I really need @redhog to help me out with it.

**Comment by afamiglietti** [comment]
I'd love to take a stab at it, but I too would need some help understanding the methods involved. Hopefully between the three of us we can work it out.

**Comment by JohnMcLear** [comment]
@afamiglietti did you get anything sorted on this?

**Comment by JohnMcLear** [comment]
Should be fixed now, give me a shout if not.
